DELETE http://localhost:3001/api/persons/1

### hand POST
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": "999999999"
}

### handle no number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dan Abramov"
}

### handle no name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "987654569"
}

### handle duplicate
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dan Abramov",
    "number": "999999999"
}